# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python Exe

on:
  push:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Python Exe
      uses: sayyid5416/pyinstaller@v1
      with:
        main: main
        artifact: Program
        use-dependencies: false
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: padrondl
        exe_path: ./dist
        python_ver: '3.9'
        spec: ./build.spec
        requirements: ./requirements.txt
        upload_exe_with_name: 'padrondl'
        options: --onefile, --name "padrondl",     
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: sayyid5416/pyinstaller@v1
        with:
          main: main
          artifact: Program
          use-dependencies: false
          exe_path: ./dist
          python_ver: '3.9'
          spec: ./build.spec
          requirements: ./requirements.txt
          upload_exe_with_name: 'padrondl'
          options: --onefile, --name "padrondl",           
          
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: padrondl
          path: dist
