# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python Exes

on:
  push:
    tags:
      - 'v*'

jobs:

  pyinstaller-win-build:
    runs-on: windows-latest
    steps:
      - name: Create Win Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/win
          upload_exe_with_name: 'padrondl-win'

  pyinstaller-linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/linux
          upload_exe_with_name: 'padrondl-linux'


  create-release:
    runs-on: ubuntu-latest
    needs:
      - pyinstaller-win-build
      - pyinstaller-linux-build
    steps:
      - name: Get commit tag
        id: get_tag
        run:  echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          TAG_NAME: ${{ steps.get_tag.outputs.TAG_NAME }}

        if: ${{ env.TAG_NAME != ''}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          # Agrega los artifacts generados como archivos adjuntos al release
          asset_paths: |
            padrondl-linux.zip
            padrondl-win.zip
          asset_names: |
            padrondl-linux.zip
            padrondl-win.zip
          asset_content_types: |
            application/zip
            application/zip
